sudo: required
dist: trusty

language: haxe
node_js: 6

os:
  - linux
    
install:

  - mkdir -p ${HOME}/haxe/versions/3.4.0
  - mv .haxerc .haxerc.ignore
  - echo '{"version":"3.4.0","resolveLibs":"scoped"}' > .haxerc
  - curl -s -L --retry 3 'http://haxe.org/website-content/downloads/3.4.0/downloads/haxe-3.4.0-linux64.tar.gz' | tar -C ${HOME}/haxe/versions/3.4.0 -x -z --strip-components=1 -f -

  - npm install haxeshim -g
  - haxe switchx.hxml
  - mv .haxerc.ignore .haxerc

  - npm install . -g
  - switchx install

script:

  - switchx list